
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


import ByteBuf from './bright/serialization/ByteBuf'

 
export enum EBlockClearTiming {
    /**
     * 无
     */
    none = 0,
    /**
     * 自己回合开始清空
     */
    owner_turn_start = 1,
    /**
     * 当前行动回合结束清空
     */
    turn_end = 2,
    /**
     * 一整轮结束清空
     */
    round_end = 3,
    /**
     * 不自动清空
     */
    never = 4,
}

 
 
export enum ECardType {
    /**
     * 无
     */
    none = 0,
    /**
     * 攻击牌
     */
    attack = 1,
    /**
     * 防御牌
     */
    defense = 2,
    /**
     * 技能牌
     */
    skill = 3,
    /**
     * 功法牌
     */
    gongfa = 4,
    /**
     * 消耗牌
     */
    consumable = 5,
    /**
     * 状态牌
     */
    status = 6,
    /**
     * 诅咒牌
     */
    curse = 7,
    /**
     * 临时牌
     */
    temp = 8,
}

 
 
export enum EDeckType {
    /**
     * 无
     */
    none = 0,
    /**
     * 武器基础牌组
     */
    weapon_basic = 1,
    /**
     * 功法牌组
     */
    gongfa = 2,
    /**
     * 消耗品牌组
     */
    consumable = 3,
    /**
     * 事件临时牌组
     */
    event = 4,
    /**
     * 测试牌组
     */
    debug = 5,
    /**
     * 混合牌组
     */
    mixed = 6,
}

 
 
export enum EEffectOwnerType {
    /**
     * 无
     */
    none = 0,
    /**
     * 卡牌
     */
    card = 1,
    /**
     * 敌人意图
     */
    enemy_intent = 2,
    /**
     * 状态
     */
    status = 3,
    /**
     * 物品
     */
    item = 4,
    /**
     * 事件
     */
    event = 5,
    /**
     * 附魔
     */
    enchant = 6,
    /**
     * 功法
     */
    gongfa = 7,
    /**
     * 战斗规则
     */
    battle_rule = 8,
}

 
 
export enum EEffectTarget {
    /**
     * 无
     */
    none = 0,
    /**
     * 效果来源自己
     */
    self = 1,
    /**
     * 玩家
     */
    player = 2,
    /**
     * 选择的敌人
     */
    selected_enemy = 3,
    /**
     * 所有敌人
     */
    all_enemies = 4,
    /**
     * 随机敌人
     */
    random_enemy = 5,
    /**
     * 全体单位
     */
    all = 6,
    /**
     * 效果来源
     */
    source = 7,
    /**
     * 当前目标
     */
    target = 8,
}

 
 
export enum EEffectType {
    /**
     * 无
     */
    none = 0,
    /**
     * 造成伤害
     */
    damage = 1,
    /**
     * 获得护盾
     */
    gain_block = 2,
    /**
     * 施加状态
     */
    apply_status = 3,
    /**
     * 抽牌
     */
    draw_card = 4,
    /**
     * 获得行动点
     */
    gain_ap = 5,
    /**
     * 恢复/获得灵力
     */
    gain_mp = 6,
    /**
     * 治疗
     */
    heal = 7,
    /**
     * 失去生命，不受护盾影响
     */
    lose_hp = 8,
    /**
     * 添加卡牌
     */
    add_card = 9,
    /**
     * 消耗卡牌
     */
    exhaust_card = 10,
    /**
     * 弃牌
     */
    discard_card = 11,
    /**
     * 修改伤害
     */
    modify_damage = 12,
    /**
     * 清除状态
     */
    clear_status = 13,
}

 
 
export enum EElement {
    /**
     * 无属性
     */
    none = 0,
    /**
     * 金
     */
    metal = 1,
    /**
     * 木
     */
    wood = 2,
    /**
     * 水
     */
    water = 3,
    /**
     * 火
     */
    fire = 4,
    /**
     * 土
     */
    earth = 5,
}

 
 
export enum EFuncID {
    /**
     *  无
     */
    none = 0,
    /**
     * 拍脸推送图
     */
    push_img = 1,
    /**
     * 商城
     */
    shop = 101001,
    /**
     * 背包
     */
    backpack = 101002,
    /**
     * 大厅
     */
    home = 101003,
}

 
 
export enum EIntentType {
    /**
     * 无
     */
    none = 0,
    /**
     * 攻击
     */
    attack = 1,
    /**
     * 防御
     */
    defend = 2,
    /**
     * 增益
     */
    buff = 3,
    /**
     * 减益
     */
    debuff = 4,
    /**
     * 攻击并减益
     */
    attack_debuff = 5,
    /**
     * 蓄力
     */
    charge = 6,
    /**
     * 特殊行动
     */
    special = 7,
    /**
     * 逃跑
     */
    escape = 8,
    /**
     * 召唤
     */
    summon = 9,
}

 
 
export enum EMainType {
    /**
     * 无
     */
    none = 0,
    /**
     * 装备
     */
    equipment = 1,
    /**
     * 消耗品
     */
    consumable = 2,
    /**
     * 材料
     */
    material = 3,
    /**
     * 宝物/贵重物
     */
    treasure = 4,
    /**
     * 任务/特殊物
     */
    quest = 5,
    /**
     * 货币
     */
    currency = 6,
    /**
     * 杂物
     */
    misc = 7,
}

 
 
export enum EQuality {
    /**
     *  无
     */
    none = 0,
    /**
     * 普通
     */
    normal = 1,
    /**
     * 优秀
     */
    excellent = 2,
    /**
     * 精良
     */
    fine = 3,
    /**
     * 稀有
     */
    rare = 4,
    /**
     * 史诗
     */
    epic = 5,
    /**
     * 传说
     */
    legendary = 6,
}

 
 
export enum EScenarioType {
    /**
     * 无
     */
    none = 0,
    /**
     * Debug 测试战斗
     */
    debug = 1,
    /**
     * 普通战斗
     */
    normal = 2,
    /**
     * 精英战斗
     */
    elite = 3,
    /**
     * Boss 战斗
     */
    boss = 4,
    /**
     * 事件战斗
     */
    event = 5,
    /**
     * 教学战斗
     */
    tutoria = 6,
}

 
 
export enum EStatusType {
    /**
     *  无
     */
    none = 0,
    /**
     * 增益
     */
    buff = 1,
    /**
     * 减益
     */
    debuff = 2,
    /**
     * 持续伤害
     */
    dot = 3,
    /**
     * 控制
     */
    control = 4,
    /**
     * 特殊
     */
    special = 5,
}

 
 
export enum ESubType {
    /**
     * 装备-无
     */
    equipment_none = 100,
    /**
     * 长剑/铁剑
     */
    weapon_sword = 101,
    /**
     * 短刃/匕首
     */
    weapon_dagger = 102,
    /**
     * 大刀
     */
    weapon_blade = 103,
    /**
     * 法杖
     */
    weapon_staff = 104,
    /**
     * 头部防具
     */
    armor_head = 105,
    /**
     * 身体防具
     */
    armor_body = 106,
    /**
     * 储物袋/背包
     */
    bag = 107,
    /**
     * 饰品
     */
    accessory = 108,
    /**
     * 其他武器
     */
    weapon_other = 109,
    /**
     * 消耗品-无
     */
    consumable_none = 200,
    /**
     * 丹药
     */
    pill = 201,
    /**
     * 五行属性石
     */
    element_stone = 202,
    /**
     * 符箓
     */
    talisman = 203,
    /**
     * 药剂/补给
     */
    medicine = 204,
    /**
     * 食物
     */
    food = 205,
    /**
     * 修理道具
     */
    repair_tool = 206,
    /**
     * 一次性卷轴
     */
    scroll_consumable = 207,
    /**
     * 材料-无
     */
    material_none = 300,
    /**
     * 灵草
     */
    herb = 301,
    /**
     * 灵果
     */
    spirit_fruit = 302,
    /**
     * 矿石/灵矿
     */
    ore = 303,
    /**
     * 妖丹/妖兽材料
     */
    monster_core = 304,
    /**
     * 炼丹辅材
     */
    alchemy_material = 305,
    /**
     * 突破材料
     */
    breakthrough_material = 306,
    /**
     * 药渣
     */
    residue = 307,
    /**
     * 灵木/藤蔓
     */
    wood_material = 308,
    /**
     * 灵铁/金属
     */
    metal_material = 309,
    /**
     * 宝物-无
     */
    treasure_none = 400,
    /**
     * 功法残卷
     */
    gongfa_fragment = 401,
    /**
     * 玉简
     */
    jade_slip = 402,
    /**
     * 丹方碎片
     */
    recipe_fragment = 403,
    /**
     * 法宝碎片
     */
    artifact_fragment = 404,
    /**
     * 古宗信物
     */
    ancient_token = 405,
    /**
     * 稀有天材地宝
     */
    rare_treasure = 406,
    /**
     * 传承物
     */
    inheritance_item = 407,
    /**
     * 特殊-无
     */
    quest_none = 500,
    /**
     * 钥匙
     */
    key = 501,
    /**
     * 通行令
     */
    pass = 502,
    /**
     * 阵旗
     */
    array_flag = 503,
    /**
     * 阵盘/阵核
     */
    array_core = 504,
    /**
     * 任务信物
     */
    quest_token = 505,
    /**
     * 地图碎片
     */
    map_fragment = 506,
    /**
     * 事件物品
     */
    event_item = 507,
    /**
     * 货币-无
     */
    currency_none = 600,
    /**
     * 劣品灵石
     */
    spirit_stone_low = 601,
    /**
     * 下品灵石
     */
    spirit_stone_normal = 602,
    /**
     * 中品灵石
     */
    spirit_stone_mid = 603,
    /**
     * 上品灵石
     */
    spirit_stone_high = 604,
    /**
     * 极品灵石
     */
    spirit_stone_top = 605,
    /**
     * 宗门贡献
     */
    sect_contribution = 606,
    /**
     * 黑市筹码
     */
    black_market_token = 607,
    /**
     * 杂物-无
     */
    misc_none = 700,
    /**
     * 杂物
     */
    junk = 701,
    /**
     * 售卖品
     */
    sell_only = 702,
    /**
     * 可分解物
     */
    dismantle = 703,
    /**
     * 文献/见闻
     */
    lore = 704,
    /**
     * 残骸/骸骨
     */
    corpse_part = 705,
}

 
 
export enum EWeaponType {
    /**
     * 无
     */
    none = 0,
    /**
     * 长剑/铁剑
     */
    sword = 1,
    /**
     * 短刃/匕首
     */
    dagger = 2,
    /**
     * 大刀
     */
    blade = 3,
    /**
     * 法杖
     */
    staff = 4,
    /**
     * 其他武器
     */
    other = 99,
}

 





/**
 * 奖励组（2个int值）
 */
export class group1 {

    constructor(_buf_: ByteBuf) {
        this.id = _buf_.ReadInt()
        this.times = _buf_.ReadInt()
    }

    /**
     * 奖池ID
     */
    readonly id: number
    /**
     * 循环掉落次数
     */
    readonly times: number

/*
    resolve(tables:Tables) {
        
        
    }
    */
}





export class IitemConfig {

    constructor(_buf_: ByteBuf) {
        this.item_id = _buf_.ReadInt()
        this.item_type = _buf_.ReadInt()
        this.sub_type = _buf_.ReadInt()
        this.quality = _buf_.ReadInt()
        this.icon = _buf_.ReadString()
        this.bag_size = _buf_.ReadInt()
    }

    /**
     * 序号
     */
    readonly item_id: number
    /**
     * 物品主类型
     */
    readonly item_type: EMainType
    /**
     * 细分类型
     */
    readonly sub_type: ESubType
    /**
     * 品质
     */
    readonly quality: number
    /**
     * 图片
     */
    readonly icon: string
    /**
     * 物品占据格子
     */
    readonly bag_size: number

/*
    resolve(tables:Tables) {
        
        
        
        
        
        
    }
    */
}





/**
 * 2个int值
 */
export class int2 {

    constructor(_buf_: ByteBuf) {
        this.v1 = _buf_.ReadInt()
        this.v2 = _buf_.ReadInt()
    }

    /**
     * 值1
     */
    readonly v1: number
    /**
     * 值2
     */
    readonly v2: number

/*
    resolve(tables:Tables) {
        
        
    }
    */
}





/**
 * 3个int值
 */
export class int3 {

    constructor(_buf_: ByteBuf) {
        this.v1 = _buf_.ReadInt()
        this.v2 = _buf_.ReadInt()
        this.v3 = _buf_.ReadInt()
    }

    /**
     * 值1
     */
    readonly v1: number
    /**
     * 值2
     */
    readonly v2: number
    /**
     * 值3
     */
    readonly v3: number

/*
    resolve(tables:Tables) {
        
        
        
    }
    */
}





export class item1 {

    constructor(_buf_: ByteBuf) {
        this.id = _buf_.ReadInt()
        this.num = _buf_.ReadInt()
    }

    /**
     * 物品id
     */
    readonly id: number
    /**
     * 物品数量
     */
    readonly num: number

/*
    resolve(tables:Tables) {
        
        
    }
    */
}





export class item2 {

    constructor(_buf_: ByteBuf) {
        this.id1 = _buf_.ReadInt()
        this.id2 = _buf_.ReadInt()
    }

    /**
     * 物品id
     */
    readonly id1: number
    /**
     * 物品id
     */
    readonly id2: number

/*
    resolve(tables:Tables) {
        
        
    }
    */
}





/**
 * 商品价格（3个int值）
 */
export class price1 {

    constructor(_buf_: ByteBuf) {
        this.currency = _buf_.ReadInt()
        this.time = _buf_.ReadInt()
        this.num = _buf_.ReadInt()
    }

    /**
     * 货币id
     */
    readonly currency: number
    /**
     * 商品时长
     */
    readonly time: number
    /**
     * 货币数量
     */
    readonly num: number

/*
    resolve(tables:Tables) {
        
        
        
    }
    */
}





/**
 * 奖励（2个int值）
 */
export class reward1 {

    constructor(_buf_: ByteBuf) {
        this.id = _buf_.ReadInt()
        this.num = _buf_.ReadInt()
    }

    /**
     * 物品id
     */
    readonly id: number
    /**
     * 物品数量
     */
    readonly num: number

/*
    resolve(tables:Tables) {
        
        
    }
    */
}





/**
 * 奖励（3个int值）
 */
export class reward2 {

    constructor(_buf_: ByteBuf) {
        this.id = _buf_.ReadInt()
        this.num = _buf_.ReadInt()
        this.weight = _buf_.ReadInt()
    }

    /**
     * 物品id
     */
    readonly id: number
    /**
     * 物品数量
     */
    readonly num: number
    /**
     * 物品获得权重
     */
    readonly weight: number

/*
    resolve(tables:Tables) {
        
        
        
    }
    */
}





/**
 * 奖励（4个int值）
 */
export class reward3 {

    constructor(_buf_: ByteBuf) {
        this.id = _buf_.ReadInt()
        this.min = _buf_.ReadInt()
        this.max = _buf_.ReadInt()
        this.prob = _buf_.ReadInt()
    }

    /**
     * 物品id
     */
    readonly id: number
    /**
     * 物品数量下限
     */
    readonly min: number
    /**
     * 物品数量上限
     */
    readonly max: number
    /**
     * 物品随机权重
     */
    readonly prob: number

/*
    resolve(tables:Tables) {
        
        
        
        
    }
    */
}





export class type1 {

    constructor(_buf_: ByteBuf) {
        this.v1 = _buf_.ReadInt()
        this.v2 = _buf_.ReadInt()
        this.str = _buf_.ReadString()
    }

    readonly v1: number
    readonly v2: number
    readonly str: string

/*
    resolve(tables:Tables) {
        
        
        
    }
    */
}





export class vector2 {

    constructor(_buf_: ByteBuf) {
        this.x = _buf_.ReadFloat()
        this.y = _buf_.ReadFloat()
    }

    readonly x: number
    readonly y: number

/*
    resolve(tables:Tables) {
        
        
    }
    */
}





export class vector3 {

    constructor(_buf_: ByteBuf) {
        this.x = _buf_.ReadFloat()
        this.y = _buf_.ReadFloat()
        this.z = _buf_.ReadFloat()
    }

    readonly x: number
    readonly y: number
    readonly z: number

/*
    resolve(tables:Tables) {
        
        
        
    }
    */
}





export class vector4 {

    constructor(_buf_: ByteBuf) {
        this.x = _buf_.ReadFloat()
        this.y = _buf_.ReadFloat()
        this.z = _buf_.ReadFloat()
        this.w = _buf_.ReadFloat()
    }

    readonly x: number
    readonly y: number
    readonly z: number
    readonly w: number

/*
    resolve(tables:Tables) {
        
        
        
        
    }
    */
}





export class xy1 {

    constructor(_buf_: ByteBuf) {
        this.x = _buf_.ReadFloat()
        this.y = _buf_.ReadFloat()
    }

    /**
     * 棋盘的x轴
     */
    readonly x: number
    /**
     * 棋盘的y轴
     */
    readonly y: number

/*
    resolve(tables:Tables) {
        
        
    }
    */
}





export class xy2 {

    constructor(_buf_: ByteBuf) {
        this.x = _buf_.ReadFloat()
        this.y = _buf_.ReadFloat()
        this.x1 = _buf_.ReadFloat()
        this.y1 = _buf_.ReadFloat()
    }

    /**
     * 棋盘A点的x轴
     */
    readonly x: number
    /**
     * 棋盘A点的y轴
     */
    readonly y: number
    /**
     * 棋盘B点的x轴
     */
    readonly x1: number
    /**
     * 棋盘B点的y轴
     */
    readonly y1: number

/*
    resolve(tables:Tables) {
        
        
        
        
    }
    */
}





export class xy3 {

    constructor(_buf_: ByteBuf) {
        this.v1 = _buf_.ReadInt()
        this.x = _buf_.ReadFloat()
        this.y = _buf_.ReadFloat()
    }

    /**
     * 值1
     */
    readonly v1: number
    /**
     * 棋盘的x轴
     */
    readonly x: number
    /**
     * 棋盘的y轴
     */
    readonly y: number

/*
    resolve(tables:Tables) {
        
        
        
    }
    */
}





export class xy4 {

    constructor(_buf_: ByteBuf) {
        this.v1 = _buf_.ReadInt()
        this.x = _buf_.ReadFloat()
        this.y = _buf_.ReadFloat()
        this.x1 = _buf_.ReadFloat()
        this.y1 = _buf_.ReadFloat()
    }

    /**
     * 值1
     */
    readonly v1: number
    /**
     * 棋盘A点的x轴
     */
    readonly x: number
    /**
     * 棋盘A点的y轴
     */
    readonly y: number
    /**
     * 文本框增加X像素长
     */
    readonly x1: number
    /**
     * 文本框增加y像素长
     */
    readonly y1: number

/*
    resolve(tables:Tables) {
        
        
        
        
        
    }
    */
}





export class xy5 {

    constructor(_buf_: ByteBuf) {
        this.v1 = _buf_.ReadInt()
        this.x = _buf_.ReadFloat()
        this.y = _buf_.ReadFloat()
        this.x1 = _buf_.ReadFloat()
        this.y1 = _buf_.ReadFloat()
    }

    /**
     * 值1
     */
    readonly v1: number
    /**
     * 棋盘A点的x轴
     */
    readonly x: number
    /**
     * 棋盘A点的y轴
     */
    readonly y: number
    /**
     * 棋盘B点的x轴
     */
    readonly x1: number
    /**
     * 棋盘B点的y轴
     */
    readonly y1: number

/*
    resolve(tables:Tables) {
        
        
        
        
        
    }
    */
}






export class item {
    private _dataMap: Map<number, IitemConfig>
	//private _dataObj: {[index:number]:IitemConfig}
    private _dataList: IitemConfig[]
    private _loaded:boolean=false;
    private _buf: ByteBuf;
    constructor(_buf_: ByteBuf) {
        this._buf = _buf_;
        this._loaded = false;
    }

    private load():void{
        if(this._loaded){
            return;
        }
        let _buf_ = this._buf;
        if(!_buf_){
            console.error("_buf_ null");
            return;
        }
        this._dataMap = new Map<number, IitemConfig>()
        this._dataList = []
		//this._dataObj = {}
        for(let n = _buf_.ReadInt(); n > 0; n--) {
            let _v: IitemConfig
            _v = new IitemConfig(_buf_)
            this._dataList.push(_v)
            this._dataMap.set(_v.item_id, _v)
			//this._dataObj[_v.item_id] = _v
        }
        this._loaded = true;
    }
    getDataMap(): Map<number, IitemConfig> {this.load(); return this._dataMap; }
	
	//getDataObj(): { [index: number]: IitemConfig } {this.load(); return this._dataObj; }
	
    getDataList(): IitemConfig[] { this.load();return this._dataList; }

    get(key: number): IitemConfig | undefined {
		this.load();
        return this._dataMap.get(key); 
    }
    
/**
    resolve(tables:Tables) {
        
    }
 */    

}




type ByteBufLoader = (file: string) => ByteBuf

export class Tables {
    private _item: item
    get item(): item  { return this._item;}

    static getTableNames(): string[] {
        let names: string[] = [];
        names.push('item');
        return names;
    }

    constructor(loader: ByteBufLoader) {
        this._item = new item(loader('item'))

        /*
        this._item.resolve(this)
        */
    }
}

