
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


import ByteBuf from './bright/serialization/ByteBuf'

 
export enum EFuncID {
    none = 0,
    /**
     * 拍脸推送图
     */
    push_img = 1,
    /**
     * 商城
     */
    shop = 101001,
    /**
     * 商城购买
     */
    shopbuy = 1010012,
    /**
     * 背包
     */
    backpack = 101002,
    /**
     * 大厅
     */
    home = 101003,
}

 
 
export enum EMainType {
    /**
     * 货币
     */
    currency = 0,
    /**
     * 头盔、护甲、背包、武器
     */
    equipment = 1,
    /**
     * 可在局内战斗中直接使用或消耗的物品
     */
    battle_consumable = 2,
    /**
     * 通过探索、搜索获得的基础或稀有材料
     */
    search_material = 3,
    /**
     * 高价值撤离物、可出售战利品
     */
    valuable_loot = 4,
    /**
     * 钥匙、通行证、任务道具等功能型物品
     */
    functional_item = 5,
}

 
 
export enum EQuality {
    /**
     * 状态较差的低品质物品，通常属性偏低，出售价值低
     */
    broken = 1,
    /**
     * 最基础的常见品质，适合前期或基础产出
     */
    common = 2,
    /**
     * 略高于普通，属性和价值有小幅提升
     */
    uncommon = 3,
    /**
     * 中期常见的高于平均水平品质
     */
    rare = 4,
    /**
     * 获取难度较高，价值和属性明显提升
     */
    epic = 5,
    /**
     * 高级品质，通常来自高风险区域或高阶来源
     */
    legendary = 6,
    /**
     * 顶级品质，极低概率或特殊玩法产出
     */
    mythic = 7,
}

 
 
export enum ESubType {
    /**
     * 装备-头盔
     */
    helmet = 101,
    /**
     * 装备-护甲
     */
    armor = 102,
    /**
     * 装备-背包
     */
    backpack = 103,
    /**
     * 装备-匕首类武器
     */
    weapon_dagger = 104,
    /**
     * 装备-手枪类武器
     */
    weapon_pistol = 105,
    /**
     * 装备-步枪类武器
     */
    weapon_rifle = 106,
    /**
     * 装备-重型武器
     */
    weapon_heavy = 107,
    /**
     * 战斗消耗-回血类道具
     */
    healing_item = 201,
    /**
     * 战斗消耗-护甲修复类
     */
    armor_repair = 202,
    /**
     * 战斗消耗-武器修理类
     */
    weapon_repair = 203,
    /**
     * 战斗消耗-武器附魔材料
     */
    elemental_stone = 204,
    /**
     * 战斗消耗-投掷类道具
     */
    throwable = 205,
    /**
     * 常见搜索材料
     */
    common_material = 301,
    /**
     * 稀有搜索材料
     */
    rare_material = 302,
    /**
     * 用于制造、升级、合成
     */
    crafting_material = 303,
    /**
     * 贵重品-宝石珠宝类
     */
    gemstone = 401,
    /**
     * 贵重品-古代文物/古币类
     */
    antique = 402,
    /**
     * 贵重品-数据、情报、芯片类
     */
    intel_item = 403,
    /**
     * 功能物-钥匙、门禁卡、撤离通行证
     */
    key_item = 501,
}

 
 
export enum ETargetType {
    /**
     * 被动物品或不可直接点击使用
     */
    none = 0,
    /**
     * 对玩家自己使用
     */
    self = 1,
    /**
     * 对敌方目标使用
     */
    enemy = 2,
    /**
     * 对场景、机关、撤离点等使用
     */
    scene = 3,
}

 





/**
 * 奖励组（2个int值）
 */
export class group1 {

    constructor(_buf_: ByteBuf) {
        this.id = _buf_.ReadInt()
        this.times = _buf_.ReadInt()
    }

    /**
     * 奖池ID
     */
    readonly id: number
    /**
     * 循环掉落次数
     */
    readonly times: number

/*
    resolve(tables:Tables) {
        
        
    }
    */
}





export class IitemConfig {

    constructor(_buf_: ByteBuf) {
        this.item_id = _buf_.ReadInt()
        this.item_type = _buf_.ReadInt()
        this.sub_type = _buf_.ReadInt()
        this.index = _buf_.ReadInt()
    }

    /**
     * 序号
     */
    readonly item_id: number
    /**
     * 物品主类型
     */
    readonly item_type: EMainType
    /**
     * 细分类型
     */
    readonly sub_type: ESubType
    readonly index: number

/*
    resolve(tables:Tables) {
        
        
        
        
    }
    */
}





/**
 * 2个int值
 */
export class int2 {

    constructor(_buf_: ByteBuf) {
        this.v1 = _buf_.ReadInt()
        this.v2 = _buf_.ReadInt()
    }

    /**
     * 值1
     */
    readonly v1: number
    /**
     * 值2
     */
    readonly v2: number

/*
    resolve(tables:Tables) {
        
        
    }
    */
}





/**
 * 3个int值
 */
export class int3 {

    constructor(_buf_: ByteBuf) {
        this.v1 = _buf_.ReadInt()
        this.v2 = _buf_.ReadInt()
        this.v3 = _buf_.ReadInt()
    }

    /**
     * 值1
     */
    readonly v1: number
    /**
     * 值2
     */
    readonly v2: number
    /**
     * 值3
     */
    readonly v3: number

/*
    resolve(tables:Tables) {
        
        
        
    }
    */
}





export class item1 {

    constructor(_buf_: ByteBuf) {
        this.id = _buf_.ReadInt()
        this.num = _buf_.ReadInt()
    }

    /**
     * 物品id
     */
    readonly id: number
    /**
     * 物品数量
     */
    readonly num: number

/*
    resolve(tables:Tables) {
        
        
    }
    */
}





export class item2 {

    constructor(_buf_: ByteBuf) {
        this.id1 = _buf_.ReadInt()
        this.id2 = _buf_.ReadInt()
    }

    /**
     * 物品id
     */
    readonly id1: number
    /**
     * 物品id
     */
    readonly id2: number

/*
    resolve(tables:Tables) {
        
        
    }
    */
}





/**
 * 商品价格（3个int值）
 */
export class price1 {

    constructor(_buf_: ByteBuf) {
        this.currency = _buf_.ReadInt()
        this.time = _buf_.ReadInt()
        this.num = _buf_.ReadInt()
    }

    /**
     * 货币id
     */
    readonly currency: number
    /**
     * 商品时长
     */
    readonly time: number
    /**
     * 货币数量
     */
    readonly num: number

/*
    resolve(tables:Tables) {
        
        
        
    }
    */
}





/**
 * 奖励（2个int值）
 */
export class reward1 {

    constructor(_buf_: ByteBuf) {
        this.id = _buf_.ReadInt()
        this.num = _buf_.ReadInt()
    }

    /**
     * 物品id
     */
    readonly id: number
    /**
     * 物品数量
     */
    readonly num: number

/*
    resolve(tables:Tables) {
        
        
    }
    */
}





/**
 * 奖励（3个int值）
 */
export class reward2 {

    constructor(_buf_: ByteBuf) {
        this.id = _buf_.ReadInt()
        this.num = _buf_.ReadInt()
        this.weight = _buf_.ReadInt()
    }

    /**
     * 物品id
     */
    readonly id: number
    /**
     * 物品数量
     */
    readonly num: number
    /**
     * 物品获得权重
     */
    readonly weight: number

/*
    resolve(tables:Tables) {
        
        
        
    }
    */
}





/**
 * 奖励（4个int值）
 */
export class reward3 {

    constructor(_buf_: ByteBuf) {
        this.id = _buf_.ReadInt()
        this.min = _buf_.ReadInt()
        this.max = _buf_.ReadInt()
        this.prob = _buf_.ReadInt()
    }

    /**
     * 物品id
     */
    readonly id: number
    /**
     * 物品数量下限
     */
    readonly min: number
    /**
     * 物品数量上限
     */
    readonly max: number
    /**
     * 物品随机权重
     */
    readonly prob: number

/*
    resolve(tables:Tables) {
        
        
        
        
    }
    */
}





export class type1 {

    constructor(_buf_: ByteBuf) {
        this.v1 = _buf_.ReadInt()
        this.v2 = _buf_.ReadInt()
        this.str = _buf_.ReadString()
    }

    readonly v1: number
    readonly v2: number
    readonly str: string

/*
    resolve(tables:Tables) {
        
        
        
    }
    */
}





export class vector2 {

    constructor(_buf_: ByteBuf) {
        this.x = _buf_.ReadFloat()
        this.y = _buf_.ReadFloat()
    }

    readonly x: number
    readonly y: number

/*
    resolve(tables:Tables) {
        
        
    }
    */
}





export class vector3 {

    constructor(_buf_: ByteBuf) {
        this.x = _buf_.ReadFloat()
        this.y = _buf_.ReadFloat()
        this.z = _buf_.ReadFloat()
    }

    readonly x: number
    readonly y: number
    readonly z: number

/*
    resolve(tables:Tables) {
        
        
        
    }
    */
}





export class vector4 {

    constructor(_buf_: ByteBuf) {
        this.x = _buf_.ReadFloat()
        this.y = _buf_.ReadFloat()
        this.z = _buf_.ReadFloat()
        this.w = _buf_.ReadFloat()
    }

    readonly x: number
    readonly y: number
    readonly z: number
    readonly w: number

/*
    resolve(tables:Tables) {
        
        
        
        
    }
    */
}





export class xy1 {

    constructor(_buf_: ByteBuf) {
        this.x = _buf_.ReadFloat()
        this.y = _buf_.ReadFloat()
    }

    /**
     * 棋盘的x轴
     */
    readonly x: number
    /**
     * 棋盘的y轴
     */
    readonly y: number

/*
    resolve(tables:Tables) {
        
        
    }
    */
}





export class xy2 {

    constructor(_buf_: ByteBuf) {
        this.x = _buf_.ReadFloat()
        this.y = _buf_.ReadFloat()
        this.x1 = _buf_.ReadFloat()
        this.y1 = _buf_.ReadFloat()
    }

    /**
     * 棋盘A点的x轴
     */
    readonly x: number
    /**
     * 棋盘A点的y轴
     */
    readonly y: number
    /**
     * 棋盘B点的x轴
     */
    readonly x1: number
    /**
     * 棋盘B点的y轴
     */
    readonly y1: number

/*
    resolve(tables:Tables) {
        
        
        
        
    }
    */
}





export class xy3 {

    constructor(_buf_: ByteBuf) {
        this.v1 = _buf_.ReadInt()
        this.x = _buf_.ReadFloat()
        this.y = _buf_.ReadFloat()
    }

    /**
     * 值1
     */
    readonly v1: number
    /**
     * 棋盘的x轴
     */
    readonly x: number
    /**
     * 棋盘的y轴
     */
    readonly y: number

/*
    resolve(tables:Tables) {
        
        
        
    }
    */
}





export class xy4 {

    constructor(_buf_: ByteBuf) {
        this.v1 = _buf_.ReadInt()
        this.x = _buf_.ReadFloat()
        this.y = _buf_.ReadFloat()
        this.x1 = _buf_.ReadFloat()
        this.y1 = _buf_.ReadFloat()
    }

    /**
     * 值1
     */
    readonly v1: number
    /**
     * 棋盘A点的x轴
     */
    readonly x: number
    /**
     * 棋盘A点的y轴
     */
    readonly y: number
    /**
     * 文本框增加X像素长
     */
    readonly x1: number
    /**
     * 文本框增加y像素长
     */
    readonly y1: number

/*
    resolve(tables:Tables) {
        
        
        
        
        
    }
    */
}





export class xy5 {

    constructor(_buf_: ByteBuf) {
        this.v1 = _buf_.ReadInt()
        this.x = _buf_.ReadFloat()
        this.y = _buf_.ReadFloat()
        this.x1 = _buf_.ReadFloat()
        this.y1 = _buf_.ReadFloat()
    }

    /**
     * 值1
     */
    readonly v1: number
    /**
     * 棋盘A点的x轴
     */
    readonly x: number
    /**
     * 棋盘A点的y轴
     */
    readonly y: number
    /**
     * 棋盘B点的x轴
     */
    readonly x1: number
    /**
     * 棋盘B点的y轴
     */
    readonly y1: number

/*
    resolve(tables:Tables) {
        
        
        
        
        
    }
    */
}






export class item {
    private _dataMap: Map<number, IitemConfig>
	//private _dataObj: {[index:number]:IitemConfig}
    private _dataList: IitemConfig[]
    private _loaded:boolean=false;
    private _buf: ByteBuf;
    constructor(_buf_: ByteBuf) {
        this._buf = _buf_;
        this._loaded = false;
    }

    private load():void{
        if(this._loaded){
            return;
        }
        let _buf_ = this._buf;
        if(!_buf_){
            console.error("_buf_ null");
            return;
        }
        this._dataMap = new Map<number, IitemConfig>()
        this._dataList = []
		//this._dataObj = {}
        for(let n = _buf_.ReadInt(); n > 0; n--) {
            let _v: IitemConfig
            _v = new IitemConfig(_buf_)
            this._dataList.push(_v)
            this._dataMap.set(_v.item_id, _v)
			//this._dataObj[_v.item_id] = _v
        }
        this._loaded = true;
    }
    getDataMap(): Map<number, IitemConfig> {this.load(); return this._dataMap; }
	
	//getDataObj(): { [index: number]: IitemConfig } {this.load(); return this._dataObj; }
	
    getDataList(): IitemConfig[] { this.load();return this._dataList; }

    get(key: number): IitemConfig | undefined {
		this.load();
        return this._dataMap.get(key); 
    }
    
/**
    resolve(tables:Tables) {
        
    }
 */    

}




type ByteBufLoader = (file: string) => ByteBuf

export class Tables {
    private _item: item
    get item(): item  { return this._item;}

    static getTableNames(): string[] {
        let names: string[] = [];
        names.push('item');
        return names;
    }

    constructor(loader: ByteBufLoader) {
        this._item = new item(loader('item'))

        /*
        this._item.resolve(this)
        */
    }
}

